name: NerdAFK
api-version: 1.20
version: ${version}
description: ${description}
website: ${url}
database: false
depend: [TAB]
softdepend: []
author: [Challenger2]
contributor: [Mats1300]
main: nu.nerd.NerdAFK.AFKPlugin

commands:
  afk:
    description: Let everyone know you are now afk
    permission: nerdafk.afk

permissions:
  nerdafk.afk:
    description: Permission to use the /afk command
  nerdafk.noautoafk:
    description: These players will never be made automatically afk
